### ISSUE TITLE
Fixing problem when configuring an IPsec tunnel

### ISSUE THREAD

**Issue by mvarrone** [aydinPython/IPsec_PA#1]
Line 101:

    stdin, stdout, stderr = ssh.exec_command(f'set network tunnel ipsec {ipsec_tunnel_name} auto-key ipsec-crypto-profile {ph2_sa)
    
should be changed to:

    stdin, stdout, stderr = ssh.exec_command(f'set network tunnel ipsec {ipsec_tunnel_name} auto-key ipsec-crypto-profile {ph2_sa}')

**Comment by aydinPython** [comment]
Hello,

Yes , thank you and I noticed that ,

only phase 1 and phase 2 profile name must be similiar on your palo alto device . 

And I will update this code tomorrow

**Comment by mvarrone** [comment]
No problem, mate!

I was a little typo :)
